Prevent the creation of multiple estimates
fastruby/points pull request #166
Opened 2021-12-10 18:08 UTC by arielj

**Description:**

This PR closes #142 by checking if there's currently an estimate for a story for the given user before creating a new estimate. If an estimage for the [story, user] already exists, the create action updates it instead of creating an new one.

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

2021-12-10 18:08 UTC, arielj commented on spec/controllers/estimates_controller_spec.rb
> +  let(:estimate) { FactoryBot.create(:estimate, story: story, user: user) }
I removed the `!` since some of the tests require the estimate to not exist now that we have the uniquness validation

2021-12-14 00:20 UTC, kindoflew commented
hi @cleicar! would you mind reviewing this when you have a chance? thanks!

2021-12-17 05:18 UTC, bronzdoc approved these changes

2021-12-18 20:55 UTC, cleicar requested changes
@arielj I was QAying this but I was able to create multiple estimates for the same story. This is the project that I was using for the tests: https://points-staging.herokuapp.com/projects/2

<img width="1435" alt="Screen Shot 2021-12-18 at 17 53 17" src="https://user-images.githubusercontent.com/11785031/146655279-db2257d1-22e9-4123-806d-db97ebcf11bc.png">

2022-01-03 20:25 UTC, arielj commented
> @arielj I was QAying this but I was able to create multiple estimates for the same story. This is the project that I was using for the tests: https://points-staging.herokuapp.com/projects/2
> 
> <img alt="Screen Shot 2021-12-18 at 17 53 17" width="1435" src="https://user-images.githubusercontent.com/11785031/146655279-db2257d1-22e9-4123-806d-db97ebcf11bc.png">

@cleicar how did you verify that 2 estimates were created? I'm checking the database and there's only one estimate for your user and that story

this won't prevent a user to open multiple `Add estimate` screens and submit the form multiple times, it takes care of that at the controller level, it updates a previous estimate if one is present instead of creating a new one (the message still says an estimate was created because it was sent to the create action, but it doesn't create more than 1 estimate)

2022-01-05 18:52 UTC, cleicar approved these changes
@arielj I think that what confused me is the displayed message, but what you said make sense. Let's leave it like that.

I can confirm that submitting a second form updates the estimates, so this is good to go!

2022-01-05 18:53 UTC, merged