Feature/project duplicate
fastruby/points pull request #42
Opened 2021-05-25 17:55 UTC by buys-fran

**Description:**

This PR closes: https://github.com/fastruby/points/issues/33

It adds a route and action for duplicating projects.
It adds a button that posts to the duplicate route.

A new `Clone Project` button was added.
Before:
![image](https://user-images.githubusercontent.com/3785596/119545405-12e87b00-bd93-11eb-8f73-4b01bc35f9d3.png)

After:
![image](https://user-images.githubusercontent.com/3785596/119545286-f0eef880-bd92-11eb-9416-6f560b5dc9f5.png)

![image](https://user-images.githubusercontent.com/3785596/119545548-3c090b80-bd93-11eb-8ccd-78b5da8ae953.png)

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

2021-05-27 12:52 UTC, buys-fran commented
@FionaDL do you mind taking a look here and letting me know if there is anything you would like to add?

2021-05-27 13:27 UTC, FionaDL requested changes
@buys-fran I think this covers everything that I was hoping for. One small grammar comment. Also, the tests are failing, looks like maybe there is a syntax error in one of the tests.

2021-05-27 13:27 UTC, FionaDL commented on spec/controllers/projects_controller_spec.rb
> +      it 'adds an success message' do
```suggestion
      it 'adds a success message' do
```

2021-05-28 11:53 UTC, buys-fran commented on spec/controllers/projects_controller_spec.rb
> +      it 'adds an success message' do
Thank you!

2021-06-01 13:14 UTC, FionaDL commented
@buys-fran looks good. @fastruby/black-bunny-brigade I approved this, but maybe someone else wants to look it over as well. It needs to be QA'ed.

2021-06-01 13:15 UTC, FionaDL approved these changes

2021-06-01 15:02 UTC, merged